pluginManagement {
    repositories {
        // 阿里云插件镜像
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        gradlePluginPortal()
    }
}

rootProject.name = 'SpringBoot'

include(
        "application",
        "common",
        "diary",
        "music",
        "article",
        "bibliophile"
)

