export { useMusicStore } from '@/music/stores/stores/musicStore'
export { useSingerStore } from '@/music/stores/stores/singerStore'
export { useCategoryStore } from '@/music/stores/stores/categoryStore'
export { useMusicPlayStore } from '@/music/stores/stores/musicPlayStore'
export { useGeneralStore } from '@/music/stores/stores/generalStore'
