spring:
  config:
    import:
      - optional:classpath:args.yaml
  application:
    name: diary
  datasource:
    diary:
      driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动
      jdbc-url: jdbc:mysql://${MYSQL-URL}/diary # 数据库地址
      username: ${MYSQL-USERNAME} #   用户
      password: ${MYSQL-PASSWORD} # 密码
      type: com.zaxxer.hikari.HikariDataSource


